### ISSUE TITLE
Allow multiple external objects to point to the same object

### ISSUE THREAD

**Issue by soniamitchell** [ScottishCovidResponse/data-registry#32]
We want to allow multiple external objects to point to the same object. Currently, there's a uniqueness constraint on the object field.

Note that, each of these external objects represent a piece of data with the same hash. If one of these pieces of data was in fact unique, there is a problem in that issues are attached to objects and it may be linked to an unrelated issue.

**Comment by alahiff** [comment]
I've changed `OneToOneField` to `ForeignKey`, enabling multiple external objects to point to the same object.

**Comment by alahiff** [comment]
Regarding your second point, maybe we should allow issues to be attached directly to external objects? At the moment only objects and object components can have issues.

**Comment by soniamitchell** [comment]
That works for me 👍 Presumably we have the same problem attaching issues to DataProducts with the same hash, so we might want to attach issues to directly to DataProduct in the same fashion?

Unless there's another reason why Issues are attached to Objects, @richardreeve ?

**Comment by richardreeve** [comment]
The justification before was that if we have multiple references to something that actually is the same result, then we want any issues raised with any of the data products or external objects to be raised with all of them simultaneously. The downside of that is that if two identical files are created which are not the same result, then we may accidentally raise issues with the wrong file...

I think we could get around that by creating a new object though (even though the new object will point to the same storage location), but we need to ensure that the right sequence of events happens in the registry when we are creating and renaming objects... does that make sense?

**Comment by soniamitchell** [comment]
So rather than multiple ExternalObjects pointing to the same Object, we have multiple Objects with the same StorageLocation?

**Comment by alahiff** [comment]
I think I prefer having multiple Objects with the same StorageLocation (not currently supported, but this can easily be changed). This makes it clearer that they are different but just happen to correspond to the same file.

**Comment by richardreeve** [comment]
I think we decided at the meeting to have both, to allow new objects for a single storage location when the files are created de novo, but also to allow multiple data products or external objects to refer to the same object when you are (for instance) doing a version bump of a file (e.g. 1.0-rc1 -> 1.0) that actually hasn't changed.

**Comment by nathan-cummings-ukaea** [comment]
Just looking to do a bit of tidying up... this issue now seems to be superseded by #44
