### ISSUE TITLE
Local registry is very chatty

### ISSUE THREAD

**Issue by soniamitchell** [ScottishCovidResponse/data-registry#33]
In R, interactions with the local registry result in lots of information being printed to the console.

Example:

```
[02/Jun/2021 09:40:26] "GET /api/issue?description=Issue%20with%20carehomes%20data%20product%20%28example%20of%20an%20issue%29.&severity=2 HTTP/1.1" 301 0
[02/Jun/2021 09:40:26] "GET /api/issue/?description=Issue%20with%20carehomes%20data%20product%20%28example%20of%20an%20issue%29.&severity=2 HTTP/1.1" 200 364
[02/Jun/2021 09:40:26] "GET /api/issue?description=Issue%20with%20carehomes%20data%20product%20%28example%20of%20an%20issue%29.&severity=2 HTTP/1.1" 301 0
[02/Jun/2021 09:40:26] "GET /api/issue/?description=Issue%20with%20carehomes%20data%20product%20%28example%20of%20an%20issue%29.&severity=2 HTTP/1.1" 200 364
[02/Jun/2021 09:40:26] "GET /api/issue?description=Issue%20with%20carehomes%20data%20product%20%28example%20of%20an%20issue%29. HTTP/1.1" 301 0
[02/Jun/2021 09:40:26] "GET /api/issue/?description=Issue%20with%20carehomes%20data%20product%20%28example%20of%20an%20issue%29. HTTP/1.1" 200 364
[02/Jun/2021 09:40:26] "GET /api/namespace?name=soniamitchell HTTP/1.1" 301 0
[02/Jun/2021 09:40:26] "GET /api/namespace/?name=soniamitchell HTTP/1.1" 200 218
[02/Jun/2021 09:40:26] "GET /api/data_product?name=records%2FSARS-CoV-2%2Fscotland%2Fcases-and-management%2Fcarehomes&version=0.20210602.0&namespace=1 HTTP/1.1" 301 0
[02/Jun/2021 09:40:26] "GET /api/data_product/?name=records%2FSARS-CoV-2%2Fscotland%2Fcases-and-management%2Fcarehomes&version=0.20210602.0&namespace=1 HTTP/1.1" 200 392
-> PATCH /api/issue/3/ HTTP/1.1
-> Host: localhost:8000
-> User-Agent: libcurl/7.64.1 r-curl/4.3.1 httr/1.4.2
-> Accept-Encoding: deflate, gzip
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/json
-> Authorization: token 360a49fc0f10e30bbdb7f78beabdc1a4e25ef5ef
-> Content-Length: 191
-> 
>> {
>>   "severity": 2,
>>   "description": "Issue with carehomes data product (example of an issue).",
>>   "object_issues": [
>>     "http://localhost:8000/api/object/28/"
>>   ],
>>   "component_issues": []
>> }

[02/Jun/2021 09:40:26] "PATCH /api/issue/3/ HTTP/1.1" 200 350
<- HTTP/1.1 200 OK
<- Date: Wed, 02 Jun 2021 09:40:26 GMT
<- Server: WSGIServer/0.2 CPython/3.7.3
<- Content-Type: application/json
<- Vary: Accept, Cookie
<- Allow: GET, PUT, PATCH, HEAD, OPTIONS
<- X-Frame-Options: DENY
<- Content-Length: 350
<- X-Content-Type-Options: nosniff
<- 
No encoding supplied: defaulting to UTF-8.
```

**Comment by nathan-cummings-ukaea** [comment]
Yeah, I'm willing to bet that this is due to the DEBUG = True setting which is necessary for the local registry to work. Not ideal, I know.

**Comment by alahiff** [comment]
@nathan-cummings-ukaea I just realised - gunicorn is installed by default in the local registry virtual environment. To run the local registry using gunicorn instead of the Django dev server you just need to run `gunicorn drams.wsgi` instead of `python manage.py runserver`. This is a more production-like way of running the local registry than using the Django dev server.

It seems fine with `DEBUG = False`, although I can't remember exactly what the problem was when we had `DEBUG = True` with the dev server.

**Comment by nathan-cummings-ukaea** [comment]
This is literally what I was just realising myself! I'll have a play and make the changes if it looks like everything works. One issue we had was with static files so I'll check that.

**Comment by alahiff** [comment]
I just found the issue with static files. There must be something we can easily do to sort that out...

https://docs.djangoproject.com/en/3.0/howto/static-files/

**Comment by nathan-cummings-ukaea** [comment]
Even when running with gunicorn?

**Comment by alahiff** [comment]
Yes. I think something's not configured properly.

**Comment by alahiff** [comment]
Actually, on the production data registry nginx is directly serving the static files without any involvement with Django or gunicorn (as mentioned here: https://docs.djangoproject.com/en/3.0/howto/static-files/deployment/)

**Comment by nathan-cummings-ukaea** [comment]
Seems to work ok using:
gunicorn drams.wsgi:application --bind 0.0.0.0:8000

@alahiff can you confirm?

**Comment by nathan-cummings-ukaea** [comment]
I having better luck using:

`gunicorn drams.wsgi:application --bind 0.0.0.0:8000`

@alahiff does that work for you as well? If so, I can make the change to the run script.

**Comment by nathan-cummings-ukaea** [comment]
Although it is much slower.

**Comment by alahiff** [comment]
@nathan-cummings-ukaea All the static files are still missing from web pages.

**Comment by alahiff** [comment]
Looking at https://stackoverflow.com/questions/12800862/how-to-make-django-serve-static-files-with-gunicorn just using gunicorn on it's own is actually not necessarily a useful improvement - it's important to have a webserver as well which talks to gunicorn and serves the static files.

Maybe there's a tiny webserver we can use instead of nginx/httpd?

**Comment by jholloc** [comment]
You could look into using the built-in python SimpleHTTPServer.

Cheers,
Jonathan

**Comment by nathan-cummings-ukaea** [comment]
I think I have found a solution to this using [whitenoise](https://pypi.org/project/whitenoise/). I'll make a branch and submit a PR.

**Comment by soniamitchell** [comment]
Wondering if I've jumped the gun on these updates? I installed a new version of the local registry and for me it continues to be chatty, `Error starting local registry` persists, and I’m unable to post an Object: 
```
Response [http://localhost:8000/api/object/]
  Date: 2021-06-04 17:04
  Status: 500
  Content-Type: text/html
  Size: 145 B

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```
though can post in other tables such as StorageRoot.
