### ISSUE TITLE
Remove "uuid": null from default JSON for creating an object

### ISSUE THREAD

**Issue by alahiff** [ScottishCovidResponse/data-registry#36]
On `/api/object/` the default JSON example for creating an object contains `uuid` set to null:
```
{
    "description": "",
    "uuid": null,
    "storage_location": null,
    "file_type": null,
    "issues": []
}
```
This gives an error because the `uuid` cannot be null. Need to ensure this line is not there.

**Comment by richardreeve** [comment]
@alahiff is there any problem with fixing this?
