### ISSUE TITLE
Enable patch on the Code Run table

### ISSUE THREAD

**Issue by alahiff** [ScottishCovidResponse/data-registry#40]
We want to register a code run at the beginning of a run, but add the input and output components to it at the end..

**Comment by richardreeve** [comment]
I think this is waiting on a discussion between @nathan-cummings-ukaea and @jholloc about how to achieve it?

**Comment by nathan-cummings-ukaea** [comment]
Yes, we had the discussion at the end of last week. I'll get on it this week.

**Comment by richardreeve** [comment]
I'm not sure the fix in #67 worked?

**Comment by nathan-cummings-ukaea** [comment]
Hi @richardreeve , sorry @soniamitchell and I sorted this out on Zulip. Can we re-close this?

**Comment by richardreeve** [comment]
Sure yes.
