### ISSUE TITLE
Remove reference between Issue and Object

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [ScottishCovidResponse/data-registry#44]

**Comment by nathan-cummings-ukaea** [comment]
This change can only be implemented after #43

**Comment by richardreeve** [comment]
@nathan-cummings-ukaea - I'm not sure why this is blocked? `ExternalObjects` will still have `ObjectComponent`s associated with them either way, so we can still raise issues... I think we can just remove this table?

**Comment by nathan-cummings-ukaea** [comment]
Closed by c661563497aa0e9d51a70294a482076d4fab5c1c
