### ISSUE TITLE
Dependency needed to install the local registry

### ISSUE THREAD

**Issue by agbeltran** [ScottishCovidResponse/data-registry#52]
There is a need to install ```graphviz``` to generate the SVG of the database schema, otherwise an error occurs:

```./rebuild-local.sh: line 9: dot: command not found```

The local registry installation needs to consider this.

**Comment by alahiff** [comment]
Unless we make a container image for the registry, I think the only option is to ask people to install graphviz if they want the schema to be generated.

**Comment by agbeltran** [comment]
Added PR to the documentation here: https://github.com/FAIRDataPipeline/FDP_hugo/pull/2
