### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by agbeltran** [ScottishCovidResponse/data-registry#62]
Tests are currently failing in ```master``` and ```develop``` branches

https://travis-ci.com/github/ScottishCovidResponse/data-registry/branches

These should be fixed in preparation for the release

**Comment by alahiff** [comment]
The integration with Travis seems to be broken. The last test run was 14 days ago and since then there have been errors like:
```
Could not authorize build request for Scottis
```
(sorry, not sure how to even view the whole message).

**Comment by alahiff** [comment]
Closing this as the tests for the master branch are now passing.

**Comment by agbeltran** [comment]
I would suggest to move to github actions

**Comment by richardreeve** [comment]
I think that's a good plan, but if the testing is working for now, we can do the switch post-1.0...
