### ISSUE TITLE
Authors - why family_name and personal_name?

### ISSUE THREAD

**Issue by alahiff** [ScottishCovidResponse/data-registry#64]
The `Author` model has two main fields for the author's name:
* `family_name`
* `personal_name`

I've always found the choice of "personal name" rather strange. As far as I can tell from Google, a personal name is a person's full name, i.e. given name(s) **and** family name, so it doesn't make any sense to have `family_name` and `personal_name` as the fields for an author's name (family name is part of a personal name)!

Shouldn't we use something like `given_name` or `given_names` instead of `personal_name`?

**Comment by richardreeve** [comment]
Completely fine by me. I don't know where that came from - looking at paperwork I have at home it's all too old to recognise that names come in different orders - in fact ORCID uses "First Name" I see! I'd just go ahead and change it if you think that's right and no-one objects?

**Comment by agbeltran** [comment]
I see that you have resolved this looking at ORCID schema @alahiff - I would recommend to use FOAF or schema.org as a reference instead (in any case, we need to have the mappings to provide any import/export functionality).

So, I would suggest ```firstName``` (like in FOAF: http://xmlns.com/foaf/spec/#term_firstName, or alternatively ```givenName``` as in https://schema.org/givenName, but it is more US-oriented) and ```familyName``` (see http://xmlns.com/foaf/spec/#term_familyName or https://schema.org/familyName). FOAF is what DCAT recommends

**Comment by alahiff** [comment]
My only problem with `firstName` and  `familyName` is that using camelCase looks weird as a variable name in Python and is not consistent with how everything else has been named.

I don't mind renaming everything to be in camelCase in JSON, however. While there doesn't seem to be a standard Google, for example, recommends using camelCase for property names in JSON: https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format. So now for authors we have:
```
        {
            "url": "http://localhost:8000/api/author/1/",
            "uuid": "93321def-2ceb-484f-bb4d-2085098b44fb",
            "last_updated": "2021-06-23T15:30:09.571183Z",
            "family_name": "Citizen",
            "given_names": "John",
            "orcid": null,
            "updated_by": "http://localhost:8000/api/users/1/",
            "orcid_url": null
        }
```
but we could change this to:
```
        {
            "url": "http://localhost:8000/api/author/1/",
            "uuid": "93321def-2ceb-484f-bb4d-2085098b44fb",
            "lastUpdated": "2021-06-23T15:30:09.571183Z",
            "familyName": "Citizen",
            "firstNme": "John",
            "orcid": null,
            "updatedBy": "http://localhost:8000/api/users/1/",
            "orcidUrl": null
        }
```
I actually prefer this.

**Comment by agbeltran** [comment]
yes, I don't mind if it is camel case or not, so ```family_name``` is fine

**Comment by agbeltran** [comment]
why do we need both ```orcid``` and ```orcidUrl```?

also, in terms of identifiers in general, I would name the field ```identifier``` in all entities, and then we have the choice of which identifier type we recommend - we can also add ```identifier_type``` (or ```identifierType``` to make that explict. 

I can open another issue for this if better

**Comment by alahiff** [comment]
Users only need to provide `orcid`, but `orcidUrl` is generated automatically for convenience. I don't mind dropping `orcidUrl`.

**Comment by agbeltran** [comment]
we should clarify what we expect in the user input (sometimes it is easier to provide the ORCID url) and IMO we should do the conversion between the numeric value and the url internally without having two fields that may end up being out of synch

**Comment by alahiff** [comment]
I'm happy to change `orcid` to `identifier` + `identifier_type`.

**Comment by alahiff** [comment]
`orcid` is the only field - `orcid_url` is actually just a function which generates the URL from the `orcid`. The example JSON provided in the browseable API looks like this:
```
{
    "uuid": "461b7346-10b7-4d2a-9d98-22b9385cbd77",
    "family_name": "",
    "given_names": "",
    "orcid": ""
}
```
(it provides a default UUID which will different each time the page is reloaded).

**Comment by alahiff** [comment]
I've replaced `given_names` with `first_name`.

**Comment by richardreeve** [comment]
So sorry - I'm feeling a bit confused about this new change @alahiff. @agbeltran's [first name link](http://xmlns.com/foaf/spec/#term_firstName) says it should be used with last name, but family name and given name is preferred.

**Comment by richardreeve** [comment]
FOAF in particular recommends [family name](http://xmlns.com/foaf/spec/#term_familyName) and [given name](http://xmlns.com/foaf/spec/#term_givenName) fwiw.

**Comment by alahiff** [comment]
I thought @agbeltran recommended first name and family name?

**Comment by richardreeve** [comment]
I think I (at least) got a bit confused because she mentioned both FOAF and first name, but in fact FOAF actually supports all of four options, but recommends family and given.

**Comment by alahiff** [comment]
I've changed `first_name` to `given_name`, so we now have `given_name` and `family_name`.

**Comment by alahiff** [comment]
Can this be closed now?

**Comment by richardreeve** [comment]
If you've merged to PR, then yes :)
