### ISSUE TITLE
localregistry.sh script?

### ISSUE THREAD

**Issue by agbeltran** [ScottishCovidResponse/data-registry#71]
The installation procedure described at: 
https://fairdatapipeline.github.io/docs/local_registry/

relies on a script ```localregistry.sh``` (at https://data.scrc.uk/static/localregistry.sh)

I don't see a script with that name at https://github.com/ScottishCovidResponse/data-registry/tree/master/scripts

are the scripts out of synch, or is the script missing from version control?

**Comment by alahiff** [comment]
It does seem to have been missing. I've added it in the `static` directory so it will be available whenever anyone installs a remote registry server.

https://github.com/ScottishCovidResponse/data-registry/commit/89d7a19836818a96bdc9773992f655590474f6bb

**Comment by agbeltran** [comment]
great, thanks @alahiff !
