### ISSUE TITLE
ORCiD and other IDs

### ISSUE THREAD

**Issue by alahiff** [ScottishCovidResponse/data-registry#74]
In https://github.com/ScottishCovidResponse/data-registry/issues/64 (now closed) the issue of author identifiers was brought up. Currently an `Author` can have an optional `orcid`, and when authors are displayed `orcid_url` is also visible (generated dynamically).

Do we want to switch to a more general identifier? e.g. either:
* `identifier` and `identifier_type`
* `identifier` (full URL, not just ID)

**Comment by richardreeve** [comment]
@agbeltran / @antony-wilson - do you have any suggestions here?

**Comment by agbeltran** [comment]
I think we should have a generic ```identifier``` field that is the full URL (so that the type can be inferred).

**Comment by alahiff** [comment]
Done https://github.com/ScottishCovidResponse/data-registry/commit/8640beba7bb538bff0000fa3ccb71302ce88501a

@agbeltran Should we do something similar for organisations? At the moment we just have a field `ror` for the ROR id.

**Comment by agbeltran** [comment]
yes, I would change ```ror``` for ```identifier```, I will check the other entities too

**Comment by agbeltran** [comment]
by the way, this makes it more future-proof and let us choose different types of identifiers for the different entities
