### ISSUE TITLE
Add identifier field to Licence

### ISSUE THREAD

**Issue by agbeltran** [ScottishCovidResponse/data-registry#77]
https://github.com/ScottishCovidResponse/data-registry/blob/8640beba7bb538bff0000fa3ccb71302ce88501a/data_management/models.py#L651

same comment as per Keyword, does ```url``` cover this?

**Comment by alahiff** [comment]
Implemented in https://github.com/ScottishCovidResponse/data-registry/commit/090180a62eb57549e7bc1c4a7f3acb828a492399
